//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ByWoggi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int rating_id { get; set; }
        public decimal star_rating { get; set; }
        public int user_id { get; set; }
        public int game_id { get; set; }
    
        public virtual User User { get; set; }
    }
}
